baseURL = "http://example.org/"
languageCode = "en-us"
theme = "bootstrap"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

DefaultContentLanguage = "ua"
defaultContentLanguageInSubdir = true

[Languages]

[Languages.ua]
languageName = "Українська"
title = "Vasko"
weight = 1

[Languages.ru]
languageName = "Русский"
title = "Vasko"
weight = 2

[Languages.en]
languageName = "English"
title = "Vasko"
weight = 3

[[Languages.ua.menu.main]]
url    = "/"
name   = "Домашня"
weight = 0

[[Languages.ua.menu.main]]
url    = "/experts/"
name   = "Ключові професіонали"
weight = 0

[[Languages.ru.menu.main]]
url    = "/"
name   = "Домашняя"
weight = 0

[[Languages.ru.menu.main]]
url    = "/experts/"
name   = "Ключевые профессионалы"
weight = 0

[[Languages.en.menu.main]]
url    = "/"
name   = "Main"
weight = 10

[[Languages.en.menu.main]]
url    = "/about/"
name   = "About The Company"
weight = 20

[[Languages.en.menu.main]]
url    = "/industries/"
name   = "Industries"
weight = 30

[[Languages.en.menu.main]]
identifier = "services"
url    = "/services/"
name   = "Services"
weight = 40

[[Languages.en.menu.main]]
url    = "/portfolio/"
name   = "Portfolio"
weight = 50

[[Languages.en.menu.main]]
url    = "/experts/"
name   = "Key Professionals"
weight = 60
