baseURL = "http://example.org/"
languageCode = "en-us"
theme = "bootstrap"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
DefaultContentLanguage = "ua"
defaultContentLanguageInSubdir = true

[blackfriday]
extensionsmask = ["autoHeaderIds", "headerIds", "autolink"]


[Languages]

[Languages.ua]
languageName = "Українська"
title = "Разом до Успіху | Vasko"
weight = 1

[Languages.ru]
languageName = "Русский"
title = "Вместе к Успеху | Vasko"
weight = 2

[Languages.en]
languageName = "English"
title = "Together to Success | Vasko"
weight = 3
