baseURL = "http://vasko.ua/"
languageCode = "en-us"
theme = "bootstrap"
Paginate = 9

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

DefaultContentLanguage = "ua"
defaultContentLanguageInSubdir = true

[blackfriday]
plainIDAnchors = false
extensionsmask = ["autoHeaderIds", "headerIds", "autolink"]


[Languages]

[Languages.ua]
languageName = "Українська"
title = "Разом до Успіху"
weight = 1

[Languages.ru]
languageName = "Русский"
title = "Вместе к Успеху"
weight = 2

[Languages.en]
languageName = "English"
title = "Together to Success"
weight = 3
