baseURL = "http://vasko.ua/"
languageCode = "en-us"
theme = "materialize"

disableKinds = ["RSS", "taxonomy"]

DefaultContentLanguage = "uk"
defaultContentLanguageInSubdir = true

[pagination]
  pagerSize = 9

[taxonomies]
  category = "categories"

[blackfriday]
  plainIDAnchors = false
  extensionsmask = ["autoHeaderIds", "headerIds", "autolink"]


[Languages]

[Languages.uk]
languageName = "Українська"
title = "Разом до Успіху"
weight = 1

[Languages.ru]
languageName = "Русский"
title = "Вместе к Успеху"
weight = 2

[Languages.en]
languageName = "English"
title = "Together to Success"
weight = 3
